# Prometheus configuration for local development
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: development
    cluster: local

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/alerts/*.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Property Upkeep API
  - job_name: 'propchain-api'
    static_configs:
      - targets: ['propchain_api:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Frontend Application
  - job_name: 'propchain-frontend'
    static_configs:
      - targets: ['propchain_frontend:3001']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Authentication Service
  - job_name: 'propchain-auth'
    static_configs:
      - targets: ['propchain_auth_mock:3002']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Background Workers
  - job_name: 'propchain-worker'
    static_configs:
      - targets: ['propchain_worker:9464']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # NGINX Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['propchain_nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Docker Container Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker_exporter:9323']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # LocalStack (AWS Services)
  - job_name: 'localstack'
    static_configs:
      - targets: ['propchain_localstack:4566']
    scrape_interval: 60s
    metrics_path: /_localstack/health
    scrape_timeout: 15s

  # MinIO Object Storage
  - job_name: 'minio'
    static_configs:
      - targets: ['propchain_minio:9000']
    scrape_interval: 30s
    metrics_path: /minio/health/live
    scrape_timeout: 10s

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true

# Remote read/write (disabled for local development)
# remote_write: []
# remote_read: []