apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    orgId: 1
    url: http://propchain_prometheus:9090
    access: proxy
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: High
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      httpHeaderName1: "X-Custom-Header"
    secureJsonData:
      httpHeaderValue1: "custom-value"